default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: derevo

development:
  <<: *default
  database: correlation_db

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
