Child.destroy_all
Child.create name: 'Бондаренко Валерія Олегівна',    risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: true,  group: 'main', zhyvit: true,  stul: true,  uzd: true,  fpk: false, disbakterioz: true,  skt_level: 1, age: 15, sex: 'female', spadkovist: true,  spadk_line1: false, spadk_line2: true,  both_parents: false, both_lines: false
Child.create name: 'Ткаченко Тимофій Олександрович', risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: true,  stul: true,  uzd: true,  fpk: true,  disbakterioz: false, skt_level: 0, age: 26, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: 'Середа Дарія Андріївна',         risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: false, skt_level: 0, age: 6,  sex: 'female', spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: 'Дегтяренко Лев Вадимович',       risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: true,  skt_level: 1, age: 16, sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: true,  both_parents: false, both_lines: true
Child.create name: "Рудой Артем Ігоревич",           risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: true,  fpk: true,  disbakterioz: true,  skt_level: 2, age: 29, sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Остапчук Аліна Олександрівна",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: false, skt_level: 0, age: 6,  sex: 'female', spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Січкар Лілія Русланівна",        risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: false, fpk: true,  disbakterioz: true,  skt_level: 2, age: 5,  sex: 'female', spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Леончук Олександр Вікторович",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: true,  fpk: false, disbakterioz: true,  skt_level: 2, age: 9,  sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: true,  both_parents: false, both_lines: true
Child.create name: "Стрельченко Валерія Олексіївна", risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: true,  fpk: false, disbakterioz: true,  skt_level: 2, age: 7,  sex: 'female', spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Книш Марія Володимирівна",       risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: true,  group: 'main', zhyvit: false, stul: true,  uzd: true,  fpk: false, disbakterioz: true,  skt_level: 3, age: 2,  sex: 'female', spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Косіцька Єлизавета Віталівна",   risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: true,  fpk: false, disbakterioz: true,  skt_level: 1, age: 5,  sex: 'female', spadkovist: true,  spadk_line1: false, spadk_line2: true,  both_parents: false, both_lines: false
Child.create name: "Зубрицький Денис Віталійович",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: false, skt_level: 0, age: 20, sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: true,  both_lines: false
Child.create name: "Міщенко Валерія Віталіївна",     risk_factor_Rasp: true,  risk_factor_AR: false, risk_factor_BA: true,  group: 'main', zhyvit: true,  stul: false, uzd: true,  fpk: true,  disbakterioz: false, skt_level: 0, age: 20, sex: 'female', spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Йовко Артур Ігоревич",           risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: true,  stul: true,  uzd: true,  fpk: true,  disbakterioz: true,  skt_level: 2, age: 7,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Писаренко Олексій Олегійович",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: true,  stul: false, uzd: false, fpk: true,  disbakterioz: true,  skt_level: 1, age: 8,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Машкін Артем Віталійович",       risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: true,  group: 'main', zhyvit: true,  stul: true,  uzd: false, fpk: true,  disbakterioz: true,  skt_level: 1, age: 32, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Житник Мілана Іванівна",         risk_factor_Rasp: true,  risk_factor_AR: false, risk_factor_BA: true,  group: 'main', zhyvit: true,  stul: true,  uzd: false, fpk: true,  disbakterioz: false, skt_level: 0, age: 26, sex: 'female', spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Мосьондз Владислав Андрійович",  risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: true,  fpk: true,  disbakterioz: true,  skt_level: 1, age: 37, sex: 'male',   spadkovist: true,  spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Пшеничний Кирил Євгеноич",       risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: true,  fpk: true,  disbakterioz: false, skt_level: 0, age: 27, sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Мамаян Давид Зурабович",         risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: false, fpk: true,  disbakterioz: true,  skt_level: 1, age: 14, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Борисов вячеслав ігорович",      risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: true,  fpk: true,  disbakterioz: false, skt_level: 0, age: 29, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Підіпригора Іван Ролманович",    risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: false, fpk: true,  disbakterioz: false, skt_level: 0, age: 33, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Рудой Артем Ігоревич",           risk_factor_Rasp: true,  risk_factor_AR: false, risk_factor_BA: true,  group: 'main', zhyvit: false, stul: false, uzd: true,  fpk: false, disbakterioz: true,  skt_level: 3, age: 31, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Коваленко матвій миколайович",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: true,  fpk: true,  disbakterioz: true,  skt_level: 1, age: 5,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Машковський іван васильович",    risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: false, fpk: false, disbakterioz: true,  skt_level: 1, age: 2,  sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Лях Ксенія михайлівна",          risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: false, skt_level: 0, age: 2,  sex: 'female', spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Тимченко Даніїл Владиславович",  risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: true,  fpk: false, disbakterioz: true,  skt_level: 1, age: 3,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Вакуленко Ярослав Михайлович",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: true,  skt_level: 2, age: 6,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Галаненко христина денисівна",   risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: true,  group: 'main', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: true,  skt_level: 1, age: 4,  sex: 'female', spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Желевицикий Михайло Ігоревий",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: false, fpk: false, disbakterioz: true,  skt_level: 2, age: 5,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Сергійчук Евген Сергійович",     risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: true,  group: 'main', zhyvit: true,  stul: false, uzd: true,  fpk: true,  disbakterioz: true,  skt_level: 1, age: 3,  sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Бондаренко Ілля Олександрович",  risk_factor_Rasp: true,  risk_factor_AR: false, risk_factor_BA: true,  group: 'main', zhyvit: true,  stul: false, uzd: true,  fpk: false, disbakterioz: false, skt_level: 0, age: 3,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Шавша. Семен Олексійович",       risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: false, fpk: false, disbakterioz: true,  skt_level: 2, age: 2,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "шестак ульна василівна",         risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: false, fpk: true,  disbakterioz: true,  skt_level: 1, age: 29, sex: 'female', spadkovist: true,  spadk_line1: true,  spadk_line2: true,  both_parents: false, both_lines: false
Child.create name: "багіова дарина ельдарівна",      risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: true,  stul: true,  uzd: false, fpk: false, disbakterioz: false, skt_level: 0, age: 8,  sex: 'female', spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Марчук Назар Тарасович",         risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: false, fpk: true,  disbakterioz: true,  skt_level: 1, age: 9,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Гитченко Назарій Ігоревич",      risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: true,  fpk: true,  disbakterioz: true,  skt_level: 3, age: 19, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false


Child.create name: "Гудзій Марія Олександрівна",      group: 'control', age: 13, sex: 'female', spadkovist: false
Child.create name: "Рукшин Ренат Станіславович",      group: 'control', age: 23, sex: 'male',   spadkovist: true
Child.create name: "Ярошенко Артем Сергійович",       group: 'control', age: 23, sex: 'male',   spadkovist: false
Child.create name: "Прядкін Максим Олександрович",    group: 'control', age: 17, sex: 'male',   spadkovist: true
Child.create name: "Сирота Тимофій Олександрович",    group: 'control', age: 33, sex: 'male',   spadkovist: false
Child.create name: "Рошка Ніколета Романівна",        group: 'control', age: 34, sex: 'female', spadkovist: false
Child.create name: "Кубасова дана Олександрівна",     group: 'control', age: 21, sex: 'female', spadkovist: false
Child.create name: "Марчук Назар Тарасович",          group: 'control', age: 25, sex: 'male',   spadkovist: false
Child.create name: "Чорноруцький марк володимирович", group: 'control', age: 3,  sex: 'male',   spadkovist: false
Child.create name: "Павлишин анастасія назарівна",    group: 'control', age: 31, sex: 'female', spadkovist: true
Child.create name: "печений евган володимирович",     group: 'control', age: 22, sex: 'male',   spadkovist: false
Child.create name: "Кушнір Ксенія Сергіївна",         group: 'control', age: 2,  sex: 'female', spadkovist: true
Child.create name: "івашко ростислва вікторович",     group: 'control', age: 1,  sex: 'male',   spadkovist: false



Child.create group: '3', name: "Бондаренко Валерія Олегівна",     age: 15, sex: "female", spadkovist: true,  spadk_line1: true,   spadk_line2: true,  both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: true,  fpk: false
Child.create group: '3', name: "Ткаченко Тимофій Олександрович",  age: 26, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: true,  stul: true,  fpk: true
Child.create group: '3', name: "Середа Дарія Андріївна",          age: 6,  sex: "female", spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: true,  fpk: false
Child.create group: '3', name: "Дегтяренко Лев Вадимович",        age: 16, sex: "male",   spadkovist: true,  spadk_line1: false,  spadk_line2: true,  both_parents: false, both_lines: true,  risk_factor_AR: true,  risk_factor_BA: true,  risk_factor_Rasp: true,  disbakterioz: true,  skt_level: 1, uzd: false, stul: true,  fpk: false
Child.create group: '3', name: "Рудой Артем Ігоревич",            age: 29, sex: "male",   spadkovist: true,  spadk_line1: false,  spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 2, uzd: true,  stul: false, fpk: 2
Child.create group: '3', name: "Остапчук Аліна Олександрівна",    age: 6,  sex: "female", spadkovist: true,  spadk_line1: false,  spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: true,  fpk: false
Child.create group: '3', name: "Січкар Лілія Русланівна",         age: 5,  sex: "female", spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 2, uzd: false, stul: false, fpk: true
Child.create group: '3', name: "Леончук Олександр Вікторович",    age: 9,  sex: "male",   spadkovist: true,  spadk_line1: false,  spadk_line2: true,  both_parents: false, both_lines: true,  risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: true,  disbakterioz: true,  skt_level: 2, uzd: true,  stul: false, fpk: false
Child.create group: '3', name: "Стрельченко Валерія Олексіївна",  age: 7,  sex: "female", spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 2, uzd: false, stul: false, fpk: false
Child.create group: '3', name: "Книш Марія Володимирівна",        age: 2,  sex: "female", spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 3, uzd: true,  stul: true,  fpk: false
Child.create group: '3', name: "Косіцька Єлизавета Віталівна",    age: 5,  sex: "female", spadkovist: true,  spadk_line1: true,   spadk_line2: true,  both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: true,  stul: true,  fpk: false
Child.create group: '3', name: "Зубрицький Денис Віталійович",    age: 20, sex: "male",   spadkovist: true,  spadk_line1: false,  spadk_line2: false, both_parents: true,  both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3', name: "Міщенко Валерія Віталіївна",      age: 20, sex: "female", spadkovist: true,  spadk_line1: false,  spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: true,  risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: true,  stul: false, fpk: true
Child.create group: '3', name: "Йовко Артур Ігоревич",            age: 7,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: true,  risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 2, uzd: true,  stul: true,  fpk: true
Child.create group: '3', name: "Писаренко Олексій Олегійович",    age: 8,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: false, stul: false, fpk: true
Child.create group: '3', name: "Машкін Артем Віталійович",        age: 32, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: false, stul: true,  fpk: true
Child.create group: '3', name: "Житник Мілана Іванівна",          age: 26, sex: "female", spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: true,  fpk: true
Child.create group: '3', name: "Гудзій Марія Олександрівна",      age: 13, sex: "female", spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3', name: "Мосьондз Владислав Андрійович",   age: 37, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: true,  stul: false, fpk: true
Child.create group: '3', name: "Рукшин Ренат Станіславович",      age: 23, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3', name: "Пшеничний Кирил Євгеноич",        age: 27, sex: "male",   spadkovist: true,  spadk_line1: false,  spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: true,  risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: true,  stul: true,  fpk: true
Child.create group: '3', name: "Ярошенко Артем Сергійович",       age: 23, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3', name: "Прядкін Максим Олександрович",    age: 17, sex: "male",   spadkovist: true,  spadk_line1: false,  spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3', name: "Мамаян Давид Зурабович",          age: 14, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: false, stul: false, fpk: true
Child.create group: '3', name: "Борисов вячеслав ігорович",       age: 29, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: true,  stul: false, fpk: true
Child.create group: '3', name: "Підіпригора Іван Ролманович",     age: 33, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: true
Child.create group: '3', name: "Сирота Тимофій Олександрович",    age: 33, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3', name: "Рошка Ніколета Романівна",        age: 34, sex: "female", spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: true,  risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3', name: "Кубасова дана Олександрівна",     age: 21, sex: "female", spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3', name: "Рудой Артем Ігоревич",            age: 31, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 3, uzd: true,  stul: false, fpk: false
Child.create group: '3', name: "Марчук Назар Тарасович",          age: 25, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3', name: "Чорноруцький марк володимирович", age: 3,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3', name: "Коваленко матвій миколайович",    age: 5,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: true,  stul: false, fpk: true
Child.create group: '3', name: "Павлишин анастасія назарівна",    age: 31, sex: "female", spadkovist: true,  spadk_line1: true,   spadk_line2: true,  both_parents: false, both_lines: false, risk_factor_AR: true,  risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3', name: "Машковський іван васильович",     age: 2,  sex: "male",   spadkovist: true,  spadk_line1: false,  spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: true,  risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: false, stul: false, fpk: false
Child.create group: '3', name: "Лях Ксенія михайлівна",           age: 2,  sex: "female", spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: true,  fpk: false
Child.create group: '3', name: "Тимченко Даніїл Владиславович",   age: 3,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: true,  stul: true,  fpk: false
Child.create group: '3', name: "Вакуленко Ярослав Михайлович",    age: 6,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 2, uzd: false, stul: true,  fpk: false
Child.create group: '3', name: "Галаненко христина денисівна",    age: 4,  sex: "female", spadkovist: true,  spadk_line1: false,  spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: false, stul: true,  fpk: false
Child.create group: '3', name: "Желевицикий Михайло Ігоревий",    age: 5,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 2, uzd: false, stul: false, fpk: false
Child.create group: '3', name: "Сергійчук Евген Сергійович",      age: 3,  sex: "male",   spadkovist: true,  spadk_line1: false,  spadk_line2: false, both_parents: true,  both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: true,  stul: false, fpk: true
Child.create group: '3', name: "Бондаренко Ілля Олександрович",   age: 3,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: true,  risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: true,  stul: false, fpk: false
Child.create group: '3', name: "Шавша. Семен Олексійович",        age: 2,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 2, uzd: false, stul: false, fpk: false
Child.create group: '3', name: "печений евган володимирович",     age: 22, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: true,  risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3', name: "шестак ульна василівна",          age: 29, sex: "female", spadkovist: true,  spadk_line1: false,  spadk_line2: true,  both_parents: false, both_lines: true,  risk_factor_AR: true,  risk_factor_BA: true,  risk_factor_Rasp: true,  disbakterioz: true,  skt_level: 1, uzd: false, stul: false, fpk: true
Child.create group: '3', name: "Кушнір Ксенія Сергіївна",         age: 2,  sex: "female", spadkovist: true,  spadk_line1: true,   spadk_line2: true,  both_parents: false, both_lines: false, risk_factor_AR: true,  risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3', name: "багіова дарина ельдарівна",       age: 8,  sex: "female", spadkovist: true,  spadk_line1: false,  spadk_line2: false, both_parents: true,  both_lines: false, risk_factor_AR: false, risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: true,  fpk: false
Child.create group: '3', name: "івашко ростислва вікторович",     age: 1,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3', name: "Марчук Назар Тарасович",          age: 9,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: false, stul: true,  fpk: true
Child.create group: '3', name: "Гитченко Назарій Ігоревич",       age: 19, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 3, uzd: true,  stul: true,  fpk: true
















































Child.create name: 'Бондаренко Валерія Олегівна',    risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: true,  group: 'main_fixed', zhyvit: true,  stul: true,  uzd: true,  fpk: false, disbakterioz: true,  skt_level: 1, age: 15, sex: 'female', spadkovist: true,  spadk_line1: false, spadk_line2: true,  both_parents: false, both_lines: false
Child.create name: 'Ткаченко Тимофій Олександрович', risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: true,  stul: true,  uzd: true,  fpk: true,  disbakterioz: false, skt_level: 0, age: 26, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: 'Середа Дарія Андріївна',         risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: false, skt_level: 0, age: 6,  sex: 'female', spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: 'Дегтяренко Лев Вадимович',       risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: true,  skt_level: 1, age: 16, sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: true,  both_parents: false, both_lines: true
Child.create name: "Рудой Артем Ігоревич",           risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: false, uzd: true,  fpk: true,  disbakterioz: true,  skt_level: 2, age: 29, sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Остапчук Аліна Олександрівна",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: false, skt_level: 0, age: 6,  sex: 'female', spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Січкар Лілія Русланівна",        risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: false, uzd: false, fpk: true,  disbakterioz: true,  skt_level: 2, age: 5,  sex: 'female', spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Леончук Олександр Вікторович",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: false, uzd: true,  fpk: false, disbakterioz: true,  skt_level: 2, age: 9,  sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: true,  both_parents: false, both_lines: true
Child.create name: "Стрельченко Валерія Олексіївна", risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: true,  uzd: true,  fpk: false, disbakterioz: true,  skt_level: 2, age: 7,  sex: 'female', spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Книш Марія Володимирівна",       risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: true,  group: 'main_fixed', zhyvit: false, stul: true,  uzd: true,  fpk: false, disbakterioz: true,  skt_level: 3, age: 2,  sex: 'female', spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Косіцька Єлизавета Віталівна",   risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: true,  uzd: true,  fpk: false, disbakterioz: true,  skt_level: 1, age: 5,  sex: 'female', spadkovist: true,  spadk_line1: false, spadk_line2: true,  both_parents: false, both_lines: false
Child.create name: "Зубрицький Денис Віталійович",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: false, skt_level: 0, age: 20, sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: true,  both_lines: false
Child.create name: "Міщенко Валерія Віталіївна",     risk_factor_Rasp: true,  risk_factor_AR: false, risk_factor_BA: true,  group: 'main_fixed', zhyvit: true,  stul: false, uzd: true,  fpk: true,  disbakterioz: false, skt_level: 0, age: 20, sex: 'female', spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Йовко Артур Ігоревич",           risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: true,  stul: true,  uzd: true,  fpk: true,  disbakterioz: true,  skt_level: 2, age: 7,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Писаренко Олексій Олегійович",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: true,  stul: false, uzd: false, fpk: true,  disbakterioz: true,  skt_level: 1, age: 8,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Машкін Артем Віталійович",       risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: true,  group: 'main_fixed', zhyvit: true,  stul: true,  uzd: false, fpk: true,  disbakterioz: true,  skt_level: 1, age: 32, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Житник Мілана Іванівна",         risk_factor_Rasp: true,  risk_factor_AR: false, risk_factor_BA: true,  group: 'main_fixed', zhyvit: true,  stul: true,  uzd: false, fpk: true,  disbakterioz: false, skt_level: 0, age: 26, sex: 'female', spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Мосьондз Владислав Андрійович",  risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: false, uzd: true,  fpk: true,  disbakterioz: true,  skt_level: 1, age: 36, sex: 'male',   spadkovist: true,  spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Пшеничний Кирил Євгеноич",       risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: true,  uzd: true,  fpk: true,  disbakterioz: false, skt_level: 0, age: 27, sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Мамаян Давид Зурабович",         risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: false, uzd: false, fpk: true,  disbakterioz: true,  skt_level: 1, age: 14, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Борисов вячеслав ігорович",      risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: false, uzd: true,  fpk: true,  disbakterioz: false, skt_level: 0, age: 29, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Підіпригора Іван Ролманович",    risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: false, uzd: false, fpk: true,  disbakterioz: false, skt_level: 0, age: 33, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Рудой Артем Ігоревич",           risk_factor_Rasp: true,  risk_factor_AR: false, risk_factor_BA: true,  group: 'main_fixed', zhyvit: false, stul: false, uzd: true,  fpk: false, disbakterioz: true,  skt_level: 3, age: 31, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Коваленко матвій миколайович",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: false, uzd: true,  fpk: true,  disbakterioz: true,  skt_level: 1, age: 5,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Машковський іван васильович",    risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: false, uzd: false, fpk: false, disbakterioz: true,  skt_level: 1, age: 2,  sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Лях Ксенія михайлівна",          risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: false, skt_level: 0, age: 2,  sex: 'female', spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Тимченко Даніїл Владиславович",  risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: true,  uzd: true,  fpk: false, disbakterioz: true,  skt_level: 1, age: 3,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Вакуленко Ярослав Михайлович",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: true,  skt_level: 2, age: 6,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Галаненко христина денисівна",   risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: true,  group: 'main_fixed', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: true,  skt_level: 1, age: 4,  sex: 'female', spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Желевицикий Михайло Ігоревий",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: false, uzd: false, fpk: false, disbakterioz: true,  skt_level: 2, age: 5,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Сергійчук Евген Сергійович",     risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: true,  group: 'main_fixed', zhyvit: true,  stul: false, uzd: true,  fpk: true,  disbakterioz: true,  skt_level: 1, age: 3,  sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Бондаренко Ілля Олександрович",  risk_factor_Rasp: true,  risk_factor_AR: false, risk_factor_BA: true,  group: 'main_fixed', zhyvit: true,  stul: false, uzd: true,  fpk: false, disbakterioz: false, skt_level: 0, age: 3,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Шавша. Семен Олексійович",       risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: false, uzd: false, fpk: false, disbakterioz: true,  skt_level: 2, age: 2,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "шестак ульна василівна",         risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: false, uzd: false, fpk: true,  disbakterioz: true,  skt_level: 1, age: 29, sex: 'female', spadkovist: true,  spadk_line1: true,  spadk_line2: true,  both_parents: false, both_lines: false
Child.create name: "багіова дарина ельдарівна",      risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: true,  stul: true,  uzd: false, fpk: false, disbakterioz: false, skt_level: 0, age: 8,  sex: 'female', spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Марчук Назар Тарасович",         risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: true,  uzd: false, fpk: true,  disbakterioz: true,  skt_level: 1, age: 9,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Гитченко Назарій Ігоревич",      risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main_fixed', zhyvit: false, stul: true,  uzd: true,  fpk: true,  disbakterioz: true,  skt_level: 3, age: 19, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false


Child.create name: "Гудзій Марія Олександрівна",      group: 'control_fixed', age: 13, sex: 'female', spadkovist: false
Child.create name: "Рукшин Ренат Станіславович",      group: 'control_fixed', age: 23, sex: 'male',   spadkovist: true
Child.create name: "Ярошенко Артем Сергійович",       group: 'control_fixed', age: 23, sex: 'male',   spadkovist: false
Child.create name: "Прядкін Максим Олександрович",    group: 'control_fixed', age: 17, sex: 'male',   spadkovist: true
Child.create name: "Сирота Тимофій Олександрович",    group: 'control_fixed', age: 33, sex: 'male',   spadkovist: false
Child.create name: "Рошка Ніколета Романівна",        group: 'control_fixed', age: 34, sex: 'female', spadkovist: false
Child.create name: "Кубасова дана Олександрівна",     group: 'control_fixed', age: 21, sex: 'female', spadkovist: false
Child.create name: "Марчук Назар Тарасович",          group: 'control_fixed', age: 25, sex: 'male',   spadkovist: false
Child.create name: "Чорноруцький марк володимирович", group: 'control_fixed', age: 3,  sex: 'male',   spadkovist: false
Child.create name: "Павлишин анастасія назарівна",    group: 'control_fixed', age: 31, sex: 'female', spadkovist: true
Child.create name: "печений евган володимирович",     group: 'control_fixed', age: 22, sex: 'male',   spadkovist: false
Child.create name: "Кушнір Ксенія Сергіївна",         group: 'control_fixed', age: 2,  sex: 'female', spadkovist: true
Child.create name: "івашко ростислва вікторович",     group: 'control_fixed', age: 1,  sex: 'male',   spadkovist: false



Child.create group: '3_fixed', name: "Бондаренко Валерія Олегівна",     age: 15, sex: "female", spadkovist: true,  spadk_line1: true,   spadk_line2: true,  both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: true,  fpk: false
Child.create group: '3_fixed', name: "Ткаченко Тимофій Олександрович",  age: 26, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: true,  stul: true,  fpk: true
Child.create group: '3_fixed', name: "Середа Дарія Андріївна",          age: 6,  sex: "female", spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: true,  fpk: false
Child.create group: '3_fixed', name: "Дегтяренко Лев Вадимович",        age: 16, sex: "male",   spadkovist: true,  spadk_line1: false,  spadk_line2: true,  both_parents: false, both_lines: true,  risk_factor_AR: true,  risk_factor_BA: true,  risk_factor_Rasp: true,  disbakterioz: true,  skt_level: 1, uzd: false, stul: true,  fpk: false
Child.create group: '3_fixed', name: "Рудой Артем Ігоревич",            age: 29, sex: "male",   spadkovist: true,  spadk_line1: false,  spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 2, uzd: true,  stul: false, fpk: 2
Child.create group: '3_fixed', name: "Остапчук Аліна Олександрівна",    age: 6,  sex: "female", spadkovist: true,  spadk_line1: false,  spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: true,  fpk: false
Child.create group: '3_fixed', name: "Січкар Лілія Русланівна",         age: 5,  sex: "female", spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 2, uzd: false, stul: false, fpk: true
Child.create group: '3_fixed', name: "Леончук Олександр Вікторович",    age: 9,  sex: "male",   spadkovist: true,  spadk_line1: false,  spadk_line2: true,  both_parents: false, both_lines: true,  risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: true,  disbakterioz: true,  skt_level: 2, uzd: true,  stul: false, fpk: false
Child.create group: '3_fixed', name: "Стрельченко Валерія Олексіївна",  age: 7,  sex: "female", spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 2, uzd: false, stul: false, fpk: false
Child.create group: '3_fixed', name: "Книш Марія Володимирівна",        age: 2,  sex: "female", spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 3, uzd: true,  stul: true,  fpk: false
Child.create group: '3_fixed', name: "Косіцька Єлизавета Віталівна",    age: 5,  sex: "female", spadkovist: true,  spadk_line1: true,   spadk_line2: true,  both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: true,  stul: true,  fpk: false
Child.create group: '3_fixed', name: "Зубрицький Денис Віталійович",    age: 20, sex: "male",   spadkovist: true,  spadk_line1: false,  spadk_line2: false, both_parents: true,  both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3_fixed', name: "Міщенко Валерія Віталіївна",      age: 20, sex: "female", spadkovist: true,  spadk_line1: false,  spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: true,  risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: true,  stul: false, fpk: true
Child.create group: '3_fixed', name: "Йовко Артур Ігоревич",            age: 7,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: true,  risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 2, uzd: true,  stul: true,  fpk: true
Child.create group: '3_fixed', name: "Писаренко Олексій Олегійович",    age: 8,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: false, stul: false, fpk: true
Child.create group: '3_fixed', name: "Машкін Артем Віталійович",        age: 32, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: false, stul: true,  fpk: true
Child.create group: '3_fixed', name: "Житник Мілана Іванівна",          age: 26, sex: "female", spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: true,  fpk: true
Child.create group: '3_fixed', name: "Гудзій Марія Олександрівна",      age: 13, sex: "female", spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3_fixed', name: "Мосьондз Владислав Андрійович",   age: 36, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: true,  stul: false, fpk: true
Child.create group: '3_fixed', name: "Рукшин Ренат Станіславович",      age: 23, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3_fixed', name: "Пшеничний Кирил Євгеноич",        age: 27, sex: "male",   spadkovist: true,  spadk_line1: false,  spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: true,  risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: true,  stul: true,  fpk: true
Child.create group: '3_fixed', name: "Ярошенко Артем Сергійович",       age: 23, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3_fixed', name: "Прядкін Максим Олександрович",    age: 17, sex: "male",   spadkovist: true,  spadk_line1: false,  spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3_fixed', name: "Мамаян Давид Зурабович",          age: 14, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: false, stul: false, fpk: true
Child.create group: '3_fixed', name: "Борисов вячеслав ігорович",       age: 29, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: true,  stul: false, fpk: true
Child.create group: '3_fixed', name: "Підіпригора Іван Ролманович",     age: 33, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: true
Child.create group: '3_fixed', name: "Сирота Тимофій Олександрович",    age: 33, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3_fixed', name: "Рошка Ніколета Романівна",        age: 34, sex: "female", spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: true,  risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3_fixed', name: "Кубасова дана Олександрівна",     age: 21, sex: "female", spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3_fixed', name: "Рудой Артем Ігоревич",            age: 31, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 3, uzd: true,  stul: false, fpk: false
Child.create group: '3_fixed', name: "Марчук Назар Тарасович",          age: 25, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3_fixed', name: "Чорноруцький марк володимирович", age: 3,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3_fixed', name: "Коваленко матвій миколайович",    age: 5,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: true,  stul: false, fpk: true
Child.create group: '3_fixed', name: "Павлишин анастасія назарівна",    age: 31, sex: "female", spadkovist: true,  spadk_line1: true,   spadk_line2: true,  both_parents: false, both_lines: false, risk_factor_AR: true,  risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3_fixed', name: "Машковський іван васильович",     age: 2,  sex: "male",   spadkovist: true,  spadk_line1: false,  spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: true,  risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: false, stul: false, fpk: false
Child.create group: '3_fixed', name: "Лях Ксенія михайлівна",           age: 2,  sex: "female", spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: true,  fpk: false
Child.create group: '3_fixed', name: "Тимченко Даніїл Владиславович",   age: 3,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: true,  stul: true,  fpk: false
Child.create group: '3_fixed', name: "Вакуленко Ярослав Михайлович",    age: 6,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 2, uzd: false, stul: true,  fpk: false
Child.create group: '3_fixed', name: "Галаненко христина денисівна",    age: 4,  sex: "female", spadkovist: true,  spadk_line1: false,  spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: false, stul: true,  fpk: false
Child.create group: '3_fixed', name: "Желевицикий Михайло Ігоревий",    age: 5,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 2, uzd: false, stul: false, fpk: false
Child.create group: '3_fixed', name: "Сергійчук Евген Сергійович",      age: 3,  sex: "male",   spadkovist: true,  spadk_line1: false,  spadk_line2: false, both_parents: true,  both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: true,  stul: false, fpk: true
Child.create group: '3_fixed', name: "Бондаренко Ілля Олександрович",   age: 3,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: true,  risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: true,  stul: false, fpk: false
Child.create group: '3_fixed', name: "Шавша. Семен Олексійович",        age: 2,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 2, uzd: false, stul: false, fpk: false
Child.create group: '3_fixed', name: "печений евган володимирович",     age: 22, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: true,  risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3_fixed', name: "шестак ульна василівна",          age: 29, sex: "female", spadkovist: true,  spadk_line1: false,  spadk_line2: true,  both_parents: false, both_lines: true,  risk_factor_AR: true,  risk_factor_BA: true,  risk_factor_Rasp: true,  disbakterioz: true,  skt_level: 1, uzd: false, stul: false, fpk: true
Child.create group: '3_fixed', name: "Кушнір Ксенія Сергіївна",         age: 2,  sex: "female", spadkovist: true,  spadk_line1: true,   spadk_line2: true,  both_parents: false, both_lines: false, risk_factor_AR: true,  risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3_fixed', name: "багіова дарина ельдарівна",       age: 8,  sex: "female", spadkovist: true,  spadk_line1: false,  spadk_line2: false, both_parents: true,  both_lines: false, risk_factor_AR: false, risk_factor_BA: true,  risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: true,  fpk: false
Child.create group: '3_fixed', name: "івашко ростислва вікторович",     age: 1,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: false, skt_level: 0, uzd: false, stul: false, fpk: false
Child.create group: '3_fixed', name: "Марчук Назар Тарасович",          age: 9,  sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 1, uzd: false, stul: true,  fpk: true
Child.create group: '3_fixed', name: "Гитченко Назарій Ігоревич",       age: 19, sex: "male",   spadkovist: false, spadk_line1: true,   spadk_line2: false, both_parents: false, both_lines: false, risk_factor_AR: false, risk_factor_BA: false, risk_factor_Rasp: false, disbakterioz: true,  skt_level: 3, uzd: true,  stul: true,  fpk: true