Child.destroy_all
Child.create name: 'Бондаренко Валерія Олегівна',    risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: true,  group: 'main', zhyvit: true,  stul: true,  uzd: true,  fpk: false, disbakterioz: true,  skt_level: 1, age: 15, sex: 'female', spadkovist: true,  spadk_line1: false, spadk_line2: true,  both_parents: false, both_lines: false
Child.create name: 'Ткаченко Тимофій Олександрович', risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: true,  stul: true,  uzd: true,  fpk: true,  disbakterioz: false, skt_level: 0, age: 26, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: 'Середа Дарія Андріївна',         risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: false, skt_level: 0, age: 6,  sex: 'female', spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: 'Дегтяренко Лев Вадимович',       risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: true,  skt_level: 1, age: 16, sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: true,  both_parents: false, both_lines: true
Child.create name: "Рудой Артем Ігоревич",           risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: true,  fpk: true,  disbakterioz: true,  skt_level: 2, age: 29, sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Остапчук Аліна Олександрівна",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: false, skt_level: 0, age: 6,  sex: 'female', spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Січкар Лілія Русланівна",        risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: false, fpk: true,  disbakterioz: true,  skt_level: 2, age: 5,  sex: 'female', spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Леончук Олександр Вікторович",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: true,  fpk: false, disbakterioz: true,  skt_level: 2, age: 9,  sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: true,  both_parents: false, both_lines: true
Child.create name: "Стрельченко Валерія Олексіївна", risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: true,  fpk: false, disbakterioz: true,  skt_level: 2, age: 7,  sex: 'female', spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Книш Марія Володимирівна",       risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: true,  group: 'main', zhyvit: false, stul: true,  uzd: true,  fpk: false, disbakterioz: true,  skt_level: 3, age: 2,  sex: 'female', spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Косіцька Єлизавета Віталівна",   risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: true,  fpk: false, disbakterioz: true,  skt_level: 1, age: 5,  sex: 'female', spadkovist: true,  spadk_line1: false, spadk_line2: true,  both_parents: false, both_lines: false
Child.create name: "Зубрицький Денис Віталійович",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: false, skt_level: 0, age: 20, sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: true,  both_lines: false
Child.create name: "Міщенко Валерія Віталіївна",     risk_factor_Rasp: true,  risk_factor_AR: false, risk_factor_BA: true,  group: 'main', zhyvit: true,  stul: false, uzd: true,  fpk: true,  disbakterioz: false, skt_level: 0, age: 20, sex: 'female', spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Йовко Артур Ігоревич",           risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: true,  stul: true,  uzd: true,  fpk: true,  disbakterioz: true,  skt_level: 2, age: 7,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Писаренко Олексій Олегійович",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: true,  stul: false, uzd: false, fpk: true,  disbakterioz: true,  skt_level: 1, age: 8,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Машкін Артем Віталійович",       risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: true,  group: 'main', zhyvit: true,  stul: true,  uzd: false, fpk: true,  disbakterioz: true,  skt_level: 1, age: 32, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Житник Мілана Іванівна",         risk_factor_Rasp: true,  risk_factor_AR: false, risk_factor_BA: true,  group: 'main', zhyvit: true,  stul: true,  uzd: false, fpk: true,  disbakterioz: false, skt_level: 0, age: 26, sex: 'female', spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Мосьондз Владислав Андрійович",  risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: true,  fpk: true,  disbakterioz: true,  skt_level: 1, age: 37, sex: 'male',   spadkovist: true,  spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Пшеничний Кирил Євгеноич",       risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: true,  fpk: true,  disbakterioz: false, skt_level: 0, age: 27, sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Мамаян Давид Зурабович",         risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: false, fpk: true,  disbakterioz: true,  skt_level: 1, age: 14, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Борисов вячеслав ігорович",      risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: true,  fpk: true,  disbakterioz: false, skt_level: 0, age: 29, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Підіпригора Іван Ролманович",    risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: false, fpk: true,  disbakterioz: false, skt_level: 0, age: 33, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Рудой Артем Ігоревич",           risk_factor_Rasp: true,  risk_factor_AR: false, risk_factor_BA: true,  group: 'main', zhyvit: false, stul: false, uzd: true,  fpk: false, disbakterioz: true,  skt_level: 3, age: 31, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Коваленко матвій миколайович",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: true,  fpk: true,  disbakterioz: true,  skt_level: 1, age: 5,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Машковський іван васильович",    risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: false, fpk: false, disbakterioz: true,  skt_level: 1, age: 2,  sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Лях Ксенія михайлівна",          risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: false, skt_level: 0, age: 2,  sex: 'female', spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Тимченко Даніїл Владиславович",  risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: true,  fpk: false, disbakterioz: true,  skt_level: 1, age: 3,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Вакуленко Ярослав Михайлович",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: true,  skt_level: 2, age: 6,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Галаненко христина денисівна",   risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: true,  group: 'main', zhyvit: false, stul: true,  uzd: false, fpk: false, disbakterioz: true,  skt_level: 1, age: 4,  sex: 'female', spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Желевицикий Михайло Ігоревий",   risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: false, fpk: false, disbakterioz: true,  skt_level: 2, age: 5,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Сергійчук Евген Сергійович",     risk_factor_Rasp: true,  risk_factor_AR: true,  risk_factor_BA: true,  group: 'main', zhyvit: true,  stul: false, uzd: true,  fpk: true,  disbakterioz: true,  skt_level: 1, age: 3,  sex: 'male',   spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Бондаренко Ілля Олександрович",  risk_factor_Rasp: true,  risk_factor_AR: false, risk_factor_BA: true,  group: 'main', zhyvit: true,  stul: false, uzd: true,  fpk: false, disbakterioz: false, skt_level: 0, age: 3,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Шавша. Семен Олексійович",       risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: false, fpk: false, disbakterioz: true,  skt_level: 2, age: 2,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "шестак ульна василівна",         risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: false, uzd: false, fpk: true,  disbakterioz: true,  skt_level: 1, age: 29, sex: 'female', spadkovist: true,  spadk_line1: true,  spadk_line2: true,  both_parents: false, both_lines: false
Child.create name: "багіова дарина ельдарівна",      risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: true,  stul: true,  uzd: false, fpk: false, disbakterioz: false, skt_level: 0, age: 8,  sex: 'female', spadkovist: true,  spadk_line1: true,  spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Марчук Назар Тарасович",         risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: false, fpk: true,  disbakterioz: true,  skt_level: 1, age: 9,  sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false
Child.create name: "Гитченко Назарій Ігоревич",      risk_factor_Rasp: false, risk_factor_AR: false, risk_factor_BA: false, group: 'main', zhyvit: false, stul: true,  uzd: true,  fpk: true,  disbakterioz: true,  skt_level: 3, age: 19, sex: 'male',   spadkovist: false, spadk_line1: false, spadk_line2: false, both_parents: false, both_lines: false


Child.create name: "Гудзій Марія Олександрівна",      group: 'control', age: 13, sex: 'female', spadkovist: false
Child.create name: "Рукшин Ренат Станіславович",      group: 'control', age: 23, sex: 'male',   spadkovist: true
Child.create name: "Ярошенко Артем Сергійович",       group: 'control', age: 23, sex: 'male',   spadkovist: false
Child.create name: "Прядкін Максим Олександрович",    group: 'control', age: 17, sex: 'male',   spadkovist: true
Child.create name: "Сирота Тимофій Олександрович",    group: 'control', age: 33, sex: 'male',   spadkovist: false
Child.create name: "Рошка Ніколета Романівна",        group: 'control', age: 34, sex: 'female', spadkovist: false
Child.create name: "Кубасова дана Олександрівна",     group: 'control', age: 21, sex: 'female', spadkovist: false
Child.create name: "Марчук Назар Тарасович",          group: 'control', age: 25, sex: 'male',   spadkovist: false
Child.create name: "Чорноруцький марк володимирович", group: 'control', age: 3,  sex: 'male',   spadkovist: false
Child.create name: "Павлишин анастасія назарівна",    group: 'control', age: 31, sex: 'female', spadkovist: true
Child.create name: "печений евган володимирович",     group: 'control', age: 22, sex: 'male',   spadkovist: false
Child.create name: "Кушнір Ксенія Сергіївна",         group: 'control', age: 2,  sex: 'female', spadkovist: true
Child.create name: "івашко ростислва вікторович",     group: 'control', age: 1,  sex: 'male',   spadkovist: false